### ISSUE TITLE
Minor bug in bankruptcy code

### ISSUE THREAD

**Issue by felenish** [Argembarger/IdleClassAutocrat#5]
Found a small bug in the bankruptcy code on line 402.

```
if(game.nextBankruptcyBonus.val() >= game.stats()[this.currentBankruptcyStatsIndex].val() * this.bankruptcyResetFraction) {						 
  this.currProcess = 0;
  game.restartGame();					
}
```

Was getting an error that game.stats was not a function. removed the () in live 402 after stats and it works fine.

**Comment by Argembarger** [comment]
Thanks @felenish ! I'm too busy to do real dev and I'm sorry I missed this for so long but I fixed it with the website editor.

I'm thinking that maybe trying to access it as a function was more tolerated in the past, or something. Not sure why I wouldn't have caught this, if it was throwing errors at the time.
